import type { Metadata } from "next";
import { Titillium_Web, Poppins } from "next/font/google";
import "./globals.css";
import Header from "./Header";
import Footer from "./footer";

const titillium = Titillium_Web({
  variable: "--font-titillium",
  subsets: ["latin"],
  weight: ["400", "600", "700"],
});

const poppins = Poppins({
  variable: "--font-poppins",
  subsets: ["latin"],
  weight: ["400", "600", "700"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${titillium.variable} ${poppins.variable} antialiased`}>
        <Header />
        <main>{children}</main>
        <Footer/>
      </body>
    </html>
  );
}
